#!/bin/sh
# Configuration
USER_DIR=/home/$USER
FOLDER=fwork/cl/brave.com/brave
PROGRAM=brave

# Execution
case $1 in
 start)
 banner $PROGRAM
 $USER_DIR/$FOLDER/$PROGRAM > /dev/null 2>&1 &
  exit 0;
  ;;
 stop)
  kill `ps aux|grep $PROGRAM|cut -f6 -d' '`
  kill `ps aux|grep $PROGRAM|cut -f7 -d' '`
  exit 0;
  ;;
 *)
  echo "Usage: $PROGRAM {start|stop}"
  exit 1;
  ;;
esac
