#!/bin/sh
# importa variaveis de uso comum
. ckvar
# execucao
echo --------------------------------------------
echo                 execucao
echo --------------------------------------------
echo configuration backup...
cp /etc/hosts $lincfg
cp /etc/stunnel/stunnel.conf $lincfg
#cp /usr/lib/oracle/10.2.0.4/client/network/admin/tnsnames.ora $lincfg
#cp $home/c/windows/system32/drivers/etc/hosts $wincfg
#cp $home/c/arquivos\ de\ programas/stunnel/stunnel.conf $wincfg 
#cp $home/c/devsuitehome_1/network/admin/tnsnames.ora $wincfg
#
# controle
echo --------------------------------------------
echo           relatorio de controle
echo --------------------------------------------
echo home: $home
echo scripts: $scripts
echo --------------------------------------------
echo wincfg: $wincfg
ls -l $wincfg
echo --------------------------------------------
echo lincfg: $lincfg
ls -l $lincfg
echo --------------------------------------------
