#!/bin/sh
echo ------------------------------------------------------------------
banner ckstart
echo ------------------------------------------------------------------
/usr/bin/owncloud &
/usr/local/sbin/start-vbox.sh > /dev/null 2>&1 &
/home/12805865839/bin/start-debian.sh > /dev/null 2>&1 &
/usr/bin/brave-browser > /dev/null 2>&1 &
/usr/bin/gnome-commander > /dev/null 2>&1 &
/home/12805865839/bin/wupdate 
/usr/bin/xeyes &
/usr/bin/libreoffice > /dev/null 2>&1 &
/home/12805865839/bin/wl 
