#!/bin/sh
echo Executando $0
DATETIME=`date +%Y%m%d%H%M%S`
echo $DATETIME - $0 >> $SCRIPTS/ck.log
cp -a $DATA/my $TO_HOME
cp -a $DATA/work $TO_HOME
cp -a $FIXED/* $TO_HOME
echo --------------------------------------------------------
echo Resultado:
ls $TO_HOME
