#!/bin/sh
case $1 in
 start)
  banner "firefox"
  banner "quantum"
  /home/12805865839/fwork/cl/firefox/firefox > /dev/null 2>&1 &
  exit 0;
  ;;
 stop)
  kill `ps aux|grep firefox|cut -f6 -d' '`
  kill `ps aux|grep firefox|cut -f7 -d' '`
  exit 0;
  ;;
 *)
  echo "Usage: f52 {start|stop}"
  exit 1;
  ;;
esac
