#!/bin/sh
# importa variaveis de uso comum
. ckvar
# execucao
echo --------------------------------------------
echo                 execucao
echo --------------------------------------------
echo mail backup...
rm -rf $data/work/Google\ Gears\ for\ Firefox/
cp -a $gears/Google\ Gears\ for\ Firefox $data/work/
#sudo rm -rf $wingears/google\ gears\ for\ firefox/
#sudo cp -a $gears/Google\ Gears\ for\ Firefox $wingears
#
# controle
echo --------------------------------------------
echo           relatorio de controle
echo --------------------------------------------
du -hs $gears/Google\ Gears\ for\ Firefox/
du -hs $data/work/Google\ Gears\ for\ Firefox/
#du -hs $wingears/Google\ Gears\ for\ Firefox/
echo --------------------------------------------
