#!/bin/sh
banner SINALDEP
SINALDEP_DIR="/home/12805865839/fwork/sistemas/SINALDEP"
INCIDENTE=$1
ANO=`date +%Y`
cd ${SINALDEP_DIR}
if [ ! -d ${ANO} ]; then
 mkdir ${ANO}
 chmod 766  ${ANO}
fi
mkdir ${ANO}/${INCIDENTE}
pwd
echo "Criando arquivos da APES..."
cp SINALDEP-SStemplate.txt ${ANO}/${INCIDENTE}/SINALDEP-${INCIDENTE}.txt
cp Select_template.sql ${ANO}/${INCIDENTE}/Select_${INCIDENTE}.sql
cp APES_template.sql ${ANO}/${INCIDENTE}/APES_${INCIDENTE}.sql
gedit ${ANO}/${INCIDENTE}/SINALDEP-${INCIDENTE}.txt &
