#!/bin/sh
stty -echo
printf "Password: "
read PASSWORD
stty echo
echo $password
printf "\n"
>  ~/dwork/resultado.txt
cd ~/d/cvs/21764dwcobranca/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 21764dwcobranca >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/29813dwrenach/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 29813dwrenach >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/39448sncrdw/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 39448sncrdw >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/37404dwsinapse/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 37404dwsinapse >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/39511dwfiscal/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 39511dwfiscal >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/21778dwdctf/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 21778dwdctf >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/39313dwrenainf/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 39313dwrenainf >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/21763dwdevsrf/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 21763dwdevsrf >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/21778dwdctfmalha/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 21778dwdctfmalha >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
cd ~/d/cvs/39356dwrenavam/01-Sistema/05-Implementacao
cvs login < $password
cvs update -d -P
echo ------------------------------------------------------------ 39356dwrenavam >> ~/dwork/resultado.txt
grep -I -n -R "\(\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\([0-9]\|[1-9][0-9]\|1[0-9]\{2\}\|2[0-4][0-9]\|25[0-5]\)" --exclude-dir="CVS" . | iconv --from=iso-8859-1 --to=utf-8 | sed -e "s/^\([^:]*\?\):\([^:]*\?\):\(.*\)$/\1;\2;\"\3\"/" -e "s/\(\w[.]\([a-zA-Z0-9#]\{1,\}\);\)/\1\2;/" | tr "\r" "_"|grep -v "Generated for Oracle"  >> ~/dwork/resultado.txt
