#!/bin/sh

# faz backup de scripts cgi
cp /usr/lib/cgi-bin/*.cgi /home/12805865839/d/fixed/work/cl/

# envia arquivos para o ownCloud
cp /home/12805865839/d/fixed/work/w*.txt /home/12805865839/ownCloud/to_cloud/sig/trance/

# gera HTML a partir de TXT
/home/12805865839/bin/trancegenw
