#!/bin/bash +x
# Script: reduz
# Autor: Marcelo Akira - akira@sistemasabertos.com.br
# extensao dos arquivos de imagem
ext='jpg'
# novo diretorio onde vao ficar as imagens convertidas
dir='novas'
# novo tamanho das imagens
tam='640x480'
mkdir $dir
for img in ``ls *.$ext``; do
 convert -resize $tam $img $dir/$img.png
done
