#!/bin/sh
# -------------------------------------------------------------
# App       : Trance
# Program   : acc02
# Function  : list access
# Site      : https://bitbucket.org/sp35000/
# Author    : Celso Kikuchi <sp35000@yahoo.com.br>
# -------------------------------------------------------------
# 20191008: initial version
# 20210105: adapting to myCloud
# 20220804: adapting to intra
# -------------------------------------------------------------
# initialize variables
sig="/home/yzmu/myCloud/ckrops/intra"
# -------------------------------------------------------------
# start
# grep -h $1 $HOME/d/mirror/truecrypt/sig/trance/*acc02.txt
grep -h $1 $sig/trance/*acc02.txt
