#!/bin/sh
# -------------------------------------------------------------
# App       : Trance
# Program   : acc01
# Function  : list username
# Site      : https://bitbucket.org/sp35000/
# Author    : Celso Kikuchi <sp35000@yahoo.com.br>
# -------------------------------------------------------------
version="20191008: initial version"
version="20210105: adapting to myCloud"
version="20220804: adapting to intra"
version="20240523: adapting to elle.conf"
# -------------------------------------------------------------
# initialize variables
msg_help="list username"
. /home/yzmu/etc/elle.conf
# -------------------------------------------------------------
# verify options and define flags
while getopts "hV" option 
do
 case $option in
  h) echo $msg_help; exit 0 ;;
  V) echo $version; exit 0 ;;
  *) exit 1;;
 esac
done
# -------------------------------------------------------------
# start
# grep -h "$1" "$HOME/d/mirror/truecrypt/sig/trance/*acc01.txt"
grep -h $1 $intra/trance/*acc01.txt
