#!/bin/sh
case $1 in
 start)
  /home/yzmu/d/cl/firefox/firefox > /dev/null 2>&1 &
  /home/12805865839/bin/f52 > /dev/null 2>&1 &
  exit 0;
  ;;
 stop)
  kill `ps aux|grep firefox|cut -f6 -d' '`
  kill `ps aux|grep firefox|cut -f7 -d' '`
  exit 0;
  ;;
 *)
  echo "Usage: /bin/f52 {start|stop}"
  exit 1;
  ;;
esac
