#!/bin/sh
# -------------------------------------------------------------
# App       : Trance
# Program   : hl
# Function  : edit Trance homelogs
# Site      : https://bitbucket.org/sp35000/
# Author    : Celso Kikuchi <sp35000@yahoo.com.br>
# -------------------------------------------------------------
# 20191231: initial version
# 20210105: including h21.html
# 20210105: adapting to myCloud
# 20220804: adapting to intra
# 20240102: automate parameters
# -------------------------------------------------------------
# initialize variables
sig="/home/yzmu/myCloud/ckrops/intra"
current=$(date +%y)
# -------------------------------------------------------------
# start
if [ -n "$1" ]; then
 vi "$sig/trance/h$1.html"
else
 vi "$sig/trance/h$current.html"
fi
