#!/bin/sh
# -------------------------------------------------------------
# App       : Elle
# Program   : t0
# Function  : turn off all drives
# Site      : https://bitbucket.org/sp35000/
# Author    : Celso Kikuchi <sp35000@yahoo.com.br>
# -------------------------------------------------------------
# 20191111: initial version
# -------------------------------------------------------------
# initialize variables
# -------------------------------------------------------------
# start
/usr/bin/truecrypt -t -d
