#!/bin/bash
# -------------------------------------------------------------
# App       : Kathryn
# Program   : w1
# Function  : mount partitions
# Site      : https://bitbucket.org/sp35000/
# Author    : Celso Kikuchi <sp35000@yahoo.com.br>
# -------------------------------------------------------------
# 20210327: improved from initial version
# 20210710: excluding r2 and w folders
# 20241230: case07 variables source and target added
# 20250120: pc18 variables source and target added
# # -------------------------------------------------------------
# initialize variables
# source="/media/yzmu/b07c0ea6-d09c-4030-9710-868b995cd3af"
# target="/media/yzmu/b07c0ea6-d09c-4030-9710-868b995cd3af/d"
source="/home/yzmu/Documents"
target="/home/yzmu/Documents"
read -s -p "box:" box
echo
#echo $box
read -s -p "cargo:" cargo
echo
#echo $cargo
#exit
# -------------------------------------------------------------
# start
echo "\n----------------------------------------------------------"
echo "Script: $0 START"
date
truecrypt -t "$source/cargo-20110512.img" "$target/v1" --fs-options="umask=0002" --password="$cargo" -k "" --protect-hidden=no
truecrypt -t "$source/cargo-20200525.img" "$target/v2" --fs-options="umask=0002" --password="$cargo" -k "" --protect-hidden=no
source="/home/yzmu/d"
target="/home/yzmu/d"
truecrypt -t "$source/box-20100711.img" "$target/r" --fs-options="umask=0002" --password="$box" -k "" --protect-hidden=no
truecrypt -t -l
df -h
date
echo "Script: $0 END"
echo "----------------------------------------------------------"

