#!/bin/sh
# -------------------------------------------------------------
# Programa  : wl
# Funcao    : Chama worklog de trabalho da Trance
#             se nao especificado o ano, chama ano atual
# Site      : https://git.serpro/12805865839/ckutils
# Autor     : Celso Kikuchi <celso.kikuchi@serpro.gov.br>
# -------------------------------------------------------------
# 20200626 - versao inicial
# -------------------------------------------------------------
# definicao de variaveis
# estacao de trabalho
DIR="/home/12805865839/ownCloud/to_cloud/sig/trance"
# home office
DIR="/home/yzmu/myCloud/ckrops/sig/trance"
# -------------------------------------------------------------
# programa
case $1 in
 06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21) vi $DIR/w$1.html;;
 *) vi $DIR/w21.html;;
esac
